function! bookmarker#help#open() abort
    echo join([
                \ 'Bookmarker',
                \ '',
                \ 'Commands:',
                \ '  :Bookmarker        Open Bookmarker',
                \ '  :Bookmarker help   Show this help',
                \ '',
                \ 'Dashboard:',
                \ '  <CR>               Open the item under the cursor',
                \ '  f                  Find files with FZF',
                \ '  /                  Search text with ripgrep',
                \ '  q                  Close Bookmarker',
                \ '',
                \ 'Quick bookmarks:',
                \ '  Press the key shown inside [ ] to open the bookmark.',
                \ '  Example: [v] ~/.vimrc -> press v',
                \ '',
                \ 'Directory bookmarks:',
                \ '  Press the key shown inside [ ] or <CR> on a directory',
                \ '  bookmark to open it with :Explore.',
                \ '',
                \ 'Search directory:',
                \ '  FZF and ripgrep search from the directory where Vim',
                \ '  was started.',
                \ '',
                \ ], "\n")
endfunction
