function! bookmarker#help#open() abort
    echo join([
                \ 'Bookmarker',
                \ '',
                \ 'Commands:',
                \ '  :Bookmarker        Open Bookmarker',
                \ '  :Bookmarker {dir}  Open Bookmarker for a directory',
                \ '  :Bookmarker help   Show this help',
                \ '',
                \ 'Dashboard:',
                \ '  <CR>               Open the item under the cursor',
                \ '  f                  Find files with FZF',
                \ '  /                  Search text with ripgrep',
                \ '  q                  Close Bookmarker',
                \ '',
                \ 'Quick bookmarks:',
                \ '  Press the key shown inside [ ] to open the bookmark.',
                \ '  Example: [v] ~/.vimrc -> press v',
                \ '',
                \ 'Directory bookmarks:',
                \ '  Press the key shown inside [ ] or <CR> on a directory',
                \ '  bookmark to open a Bookmarker page for that folder.',
                \ '',
                \ 'Folder pages:',
                \ '  Configure g:bookmarker_folder_bookmarks to give each',
                \ '  directory its own file bookmarks and child folders.',
                \ '',
                \ 'Search directory:',
                \ '  FZF and ripgrep search from the active dashboard',
                \ '  directory.',
                \ '',
                \ ], "\n")
endfunction
